// Job Notification Tracker - Realistic Indian Tech Jobs Dataset

const jobsData = [
    {
        id: 1,
        title: "SDE Intern",
        company: "Amazon",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Java", "Data Structures", "Algorithms"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://amazon.jobs/en/jobs/intern-sde",
        description: "Join Amazon's engineering team as an SDE Intern. Work on scalable systems and learn from experienced engineers. Strong problem-solving skills required. Opportunity to convert to full-time role."
    },
    {
        id: 2,
        title: "Graduate Engineer Trainee",
        company: "Infosys",
        location: "Mysore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Web Development"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "3–5 LPA",
        applyUrl: "https://infosys.com/careers/get",
        description: "Infosys is hiring fresh graduates for our training program. Comprehensive 3-month training followed by project deployment. Work with global clients on cutting-edge technology projects."
    },
    {
        id: 3,
        title: "Frontend Developer Intern",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "JavaScript", "CSS"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30k–₹50k/month Internship",
        applyUrl: "https://razorpay.com/jobs/frontend-intern",
        description: "Build beautiful payment interfaces at India's leading fintech. Work with React and modern frontend tools. Mentorship from senior engineers. Fast-paced startup environment with learning opportunities."
    },
    {
        id: 4,
        title: "Junior Backend Developer",
        company: "Flipkart",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Python", "Django", "REST API"],
        source: "Indeed",
        postedDaysAgo: 3,
        salaryRange: "6–10 LPA",
        applyUrl: "https://flipkart.com/careers/backend-dev",
        description: "Join Flipkart's backend team to build scalable e-commerce systems. Work on microservices architecture and handle millions of transactions. Collaborative team environment with growth opportunities."
    },
    {
        id: 5,
        title: "QA Intern",
        company: "TCS",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Manual Testing", "Selenium", "Java"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "₹15k–₹25k/month Internship",
        applyUrl: "https://tcs.com/careers/qa-intern",
        description: "Learn software testing at TCS. Hands-on experience with automation tools and testing frameworks. Work on enterprise projects for global clients. Training provided for freshers."
    },
    {
        id: 6,
        title: "Data Analyst Intern",
        company: "Swiggy",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "SQL", "Excel"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://swiggy.com/careers/data-analyst",
        description: "Analyze food delivery data and generate insights. Work with large datasets and visualization tools. Learn from experienced data scientists. Impact millions of users with your analysis."
    },
    {
        id: 7,
        title: "Java Developer",
        company: "Wipro",
        location: "Hyderabad",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 2,
        salaryRange: "3–5 LPA",
        applyUrl: "https://wipro.com/careers/java-developer",
        description: "Develop enterprise Java applications for global clients. Work with Spring framework and microservices. Opportunity to work on banking and healthcare projects. Supportive learning environment."
    },
    {
        id: 8,
        title: "React Developer",
        company: "PhonePe",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Redux", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://phonepe.com/careers/react-dev",
        description: "Build India's most-used payment app. Work on high-performance React applications serving 400M+ users. Modern tech stack with TypeScript and Redux. Fast-paced fintech environment with excellent compensation."
    },
    {
        id: 9,
        title: "Python Developer",
        company: "Zoho",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Django", "PostgreSQL"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "3–5 LPA",
        applyUrl: "https://zoho.com/careers/python-fresher",
        description: "Join Zoho's product development team. Build SaaS applications used by millions worldwide. Learn from experienced developers in a product-focused company. No service-based projects."
    },
    {
        id: 10,
        title: "Full Stack Intern",
        company: "CRED",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["JavaScript", "Node.js", "React"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "₹35k–₹50k/month Internship",
        applyUrl: "https://cred.club/careers/fullstack-intern",
        description: "Work on CRED's premium fintech platform. Build features for India's most trusted members. Modern tech stack and design-first culture. High-quality codebase with excellent mentorship."
    },
    {
        id: 11,
        title: "DevOps Intern",
        company: "Paytm",
        location: "Noida",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Linux", "Docker", "AWS"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "₹20k–₹30k/month Internship",
        applyUrl: "https://paytm.com/careers/devops-intern",
        description: "Learn DevOps at scale with Paytm. Work with cloud infrastructure and CI/CD pipelines. Hands-on experience with AWS and containerization. Mentorship from senior DevOps engineers."
    },
    {
        id: 12,
        title: "Android Developer",
        company: "Freshworks",
        location: "Chennai",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Kotlin", "Android SDK", "MVVM"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        applyUrl: "https://freshworks.com/careers/android-dev",
        description: "Build mobile apps for Freshworks' SaaS products. Work with modern Android development practices. Collaborative team with focus on code quality. Global product company with strong engineering culture."
    },
    {
        id: 13,
        title: "UI/UX Designer Intern",
        company: "Juspay",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Figma", "UI Design", "Prototyping"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://juspay.in/careers/ui-intern",
        description: "Design payment experiences for millions of users. Work with product and engineering teams. Learn from experienced designers. Portfolio-building opportunity in fintech."
    },
    {
        id: 14,
        title: "Software Engineer Trainee",
        company: "Accenture",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Cloud"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3–5 LPA",
        applyUrl: "https://accenture.com/careers/trainee",
        description: "Join Accenture's technology consulting practice. Comprehensive training program followed by client projects. Work with Fortune 500 companies. Global exposure and career growth opportunities."
    },
    {
        id: 15,
        title: "Machine Learning Intern",
        company: "IBM",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "TensorFlow", "Machine Learning"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://ibm.com/careers/ml-intern",
        description: "Work on AI and ML projects at IBM Research. Access to cutting-edge technology and research papers. Mentorship from PhD researchers. Opportunity to publish research work."
    },
    {
        id: 16,
        title: "Backend Engineer",
        company: "Capgemini",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Node.js", "MongoDB", "REST API"],
        source: "Naukri",
        postedDaysAgo: 7,
        salaryRange: "3–5 LPA",
        applyUrl: "https://capgemini.com/careers/backend-eng",
        description: "Develop backend systems for enterprise clients. Work with modern JavaScript frameworks. Exposure to multiple domains including banking and retail. Training and certification opportunities."
    },
    {
        id: 17,
        title: "Frontend Developer",
        company: "Oracle",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "JavaScript", "HTML/CSS"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        applyUrl: "https://oracle.com/careers/frontend-dev",
        description: "Build user interfaces for Oracle Cloud applications. Work with React and modern frontend tools. Collaborate with global teams. Excellent benefits and work-life balance."
    },
    {
        id: 18,
        title: "Data Science Intern",
        company: "Cognizant",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Python", "Pandas", "Statistics"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://cognizant.com/careers/ds-intern",
        description: "Learn data science in a corporate environment. Work on real client projects with structured mentorship. Training in ML and analytics tools. Potential for full-time conversion."
    },
    {
        id: 19,
        title: "iOS Developer",
        company: "SAP",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Swift", "iOS SDK", "UIKit"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "10–18 LPA",
        applyUrl: "https://sap.com/careers/ios-developer",
        description: "Develop mobile apps for SAP's enterprise solutions. Work with Swift and modern iOS frameworks. Global product development with excellent compensation. Strong engineering culture."
    },
    {
        id: 20,
        title: "Cloud Engineer Intern",
        company: "Dell",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["AWS", "Linux", "Networking"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://dell.com/careers/cloud-intern",
        description: "Learn cloud computing at Dell Technologies. Hands-on experience with AWS and Azure. Work on infrastructure automation. Certification support and career development."
    },
    {
        id: 21,
        title: "Graduate Engineer Trainee",
        company: "Tech Mahindra",
        location: "Pune",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Python", "SQL"],
        source: "Naukri",
        postedDaysAgo: 0,
        salaryRange: "3–5 LPA",
        applyUrl: "https://techmahindra.com/careers/get",
        description: "Join Tech Mahindra's engineering program. Structured training followed by project assignments. Work on telecom and digital transformation projects. Good work-life balance."
    },
    {
        id: 22,
        title: "React Native Developer",
        company: "Meesho",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React Native", "JavaScript", "Redux"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "https://meesho.com/careers/rn-developer",
        description: "Build mobile apps for India's fastest-growing social commerce platform. Work with React Native and modern mobile development practices. Impact millions of resellers and customers."
    },
    {
        id: 23,
        title: "Security Analyst Intern",
        company: "HCL Technologies",
        location: "Noida",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Cybersecurity", "Networking", "Linux"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "₹18k–₹30k/month Internship",
        applyUrl: "https://hcltech.com/careers/security-intern",
        description: "Learn cybersecurity at HCL. Work on security audits and vulnerability assessments. Training in ethical hacking and security tools. Certification support provided."
    },
    {
        id: 24,
        title: "Full Stack Developer",
        company: "Ola",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Node.js", "React", "MongoDB"],
        source: "Indeed",
        postedDaysAgo: 1,
        salaryRange: "10–18 LPA",
        applyUrl: "https://ola.com/careers/fullstack-dev",
        description: "Build features for Ola's mobility platform. Work on both frontend and backend systems. Fast-paced startup environment with modern tech stack. Solve real-world transportation problems."
    },
    {
        id: 25,
        title: "Business Analyst Intern",
        company: "Deloitte",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Excel", "SQL", "Business Analysis"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://deloitte.com/careers/ba-intern",
        description: "Work with consulting teams on business analysis projects. Learn requirements gathering and process improvement. Exposure to multiple industries. Structured training program."
    },
    {
        id: 26,
        title: "Java Backend Developer",
        company: "Mindtree",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Java", "Spring Boot", "Microservices"],
        source: "Naukri",
        postedDaysAgo: 6,
        salaryRange: "3–5 LPA",
        applyUrl: "https://mindtree.com/careers/java-backend",
        description: "Develop microservices for enterprise clients. Work with Spring ecosystem and cloud technologies. Collaborative team environment. Focus on code quality and best practices."
    },
    {
        id: 27,
        title: "Product Analyst Intern",
        company: "Zomato",
        location: "Gurgaon",
        mode: "Remote",
        experience: "Fresher",
        skills: ["SQL", "Python", "Analytics"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://zomato.com/careers/product-analyst",
        description: "Analyze product metrics and user behavior at Zomato. Work with product managers and engineers. Learn A/B testing and experimentation. Impact product decisions with data."
    },
    {
        id: 28,
        title: "Angular Developer",
        company: "LTI",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Angular", "TypeScript", "RxJS"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "6–10 LPA",
        applyUrl: "https://lti.com/careers/angular-dev",
        description: "Build enterprise web applications with Angular. Work on banking and financial services projects. Modern development practices and tools. Good work-life balance."
    },
    {
        id: 29,
        title: "Automation Tester",
        company: "Mphasis",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["Selenium", "Java", "TestNG"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "3–5 LPA",
        applyUrl: "https://mphasis.com/careers/automation-tester",
        description: "Automate testing for enterprise applications. Work with Selenium and modern testing frameworks. Learn CI/CD integration. Structured career path in QA."
    },
    {
        id: 30,
        title: "Backend Developer Intern",
        company: "Dunzo",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "Django", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://dunzo.com/careers/backend-intern",
        description: "Build backend systems for hyperlocal delivery. Work with Python and modern frameworks. Fast-paced startup with learning opportunities. Solve complex logistics problems."
    },
    {
        id: 31,
        title: "DevOps Engineer",
        company: "Nagarro",
        location: "Gurgaon",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Docker", "Kubernetes", "Jenkins"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "6–10 LPA",
        applyUrl: "https://nagarro.com/careers/devops-eng",
        description: "Manage CI/CD pipelines and cloud infrastructure. Work with containerization and orchestration tools. Collaborative DevOps culture. Opportunity to work with global clients."
    },
    {
        id: 32,
        title: "Mobile App Developer Intern",
        company: "Urban Company",
        location: "Gurgaon",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Flutter", "Dart", "Mobile Development"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://urbancompany.com/careers/mobile-intern",
        description: "Build mobile apps with Flutter for India's leading home services platform. Work on features used by millions. Modern tech stack and agile development. Great learning environment."
    },
    {
        id: 33,
        title: "Software Developer",
        company: "Persistent Systems",
        location: "Pune",
        mode: "Onsite",
        experience: "0-1",
        skills: ["C++", "Python", "Algorithms"],
        source: "Indeed",
        postedDaysAgo: 4,
        salaryRange: "3–5 LPA",
        applyUrl: "https://persistent.com/careers/software-dev",
        description: "Develop software solutions for global product companies. Work on cutting-edge technology projects. Strong focus on innovation and R&D. Good learning opportunities."
    },
    {
        id: 34,
        title: "Frontend Engineer",
        company: "Groww",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["React", "Next.js", "TypeScript"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–18 LPA",
        applyUrl: "https://groww.in/careers/frontend-eng",
        description: "Build investment platform for millions of Indians. Work with modern React and Next.js. Performance-focused development. Fast-growing fintech with excellent culture."
    },
    {
        id: 35,
        title: "Data Engineer Intern",
        company: "Walmart Labs",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Python", "Spark", "SQL"],
        source: "Naukri",
        postedDaysAgo: 5,
        salaryRange: "₹35k–₹50k/month Internship",
        applyUrl: "https://walmartlabs.com/careers/data-intern",
        description: "Work on big data pipelines at Walmart Labs. Learn Spark and distributed computing. Solve problems at massive scale. Excellent mentorship and learning resources."
    },
    {
        id: 36,
        title: "QA Automation Engineer",
        company: "Publicis Sapient",
        location: "Gurgaon",
        mode: "Onsite",
        experience: "1-3",
        skills: ["Selenium", "Java", "API Testing"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        applyUrl: "https://publicissapient.com/careers/qa-automation",
        description: "Automate testing for digital transformation projects. Work with modern testing frameworks and tools. Exposure to multiple industries. Collaborative work environment."
    },
    {
        id: 37,
        title: "Backend Developer",
        company: "Postman",
        location: "Bangalore",
        mode: "Remote",
        experience: "1-3",
        skills: ["Node.js", "MongoDB", "GraphQL"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://postman.com/careers/backend-dev",
        description: "Build API development tools used by millions of developers worldwide. Work with Node.js and modern backend technologies. Remote-first culture. Global product company."
    },
    {
        id: 38,
        title: "Cloud Solutions Intern",
        company: "Microsoft",
        location: "Hyderabad",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Azure", "Cloud Computing", "Python"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "₹40k–₹60k/month Internship",
        applyUrl: "https://microsoft.com/careers/cloud-intern",
        description: "Work on Azure cloud solutions at Microsoft. Learn cloud architecture and services. Mentorship from experienced engineers. Opportunity to work on cutting-edge technology."
    },
    {
        id: 39,
        title: "Full Stack Developer",
        company: "Hashedin",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["JavaScript", "React", "Node.js"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "3–5 LPA",
        applyUrl: "https://hashedin.com/careers/fullstack-dev",
        description: "Develop full stack applications for product companies. Work with modern JavaScript frameworks. Strong engineering culture. Focus on clean code and best practices."
    },
    {
        id: 40,
        title: "Machine Learning Engineer",
        company: "Navi",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Python", "TensorFlow", "ML"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–18 LPA",
        applyUrl: "https://navi.com/careers/ml-engineer",
        description: "Build ML models for fintech products. Work on credit scoring and fraud detection. Modern ML infrastructure. Fast-growing company with strong tech culture."
    },
    {
        id: 41,
        title: "Software Engineer Intern",
        company: "Adobe",
        location: "Noida",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["C++", "Java", "Algorithms"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "₹40k–₹60k/month Internship",
        applyUrl: "https://adobe.com/careers/swe-intern",
        description: "Work on Adobe's creative software products. Learn from world-class engineers. Challenging problems and cutting-edge technology. Excellent compensation and benefits."
    },
    {
        id: 42,
        title: "Python Backend Developer",
        company: "Cure.fit",
        location: "Bangalore",
        mode: "Remote",
        experience: "0-1",
        skills: ["Python", "FastAPI", "PostgreSQL"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        applyUrl: "https://curefit.com/careers/python-backend",
        description: "Build health and fitness platform backend. Work with Python and modern frameworks. Impact millions of users' health journey. Startup environment with good work culture."
    },
    {
        id: 43,
        title: "React Developer Intern",
        company: "Licious",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["React", "JavaScript", "Redux"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://licious.com/careers/react-intern",
        description: "Build e-commerce platform for fresh meat delivery. Work with React and modern frontend tools. Fast-paced D2C startup. Learn from experienced developers."
    },
    {
        id: 44,
        title: "Site Reliability Engineer",
        company: "Atlassian",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Linux", "Python", "Kubernetes"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–18 LPA",
        applyUrl: "https://atlassian.com/careers/sre",
        description: "Ensure reliability of Atlassian's products. Work with distributed systems and cloud infrastructure. Global team collaboration. Excellent engineering culture and benefits."
    },
    {
        id: 45,
        title: "Java Developer Intern",
        company: "Myntra",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Spring", "MySQL"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://myntra.com/careers/java-intern",
        description: "Work on India's leading fashion e-commerce platform. Build scalable backend systems. Learn microservices architecture. Part of Flipkart group with strong tech culture."
    },
    {
        id: 46,
        title: "Frontend Developer",
        company: "Browserstack",
        location: "Mumbai",
        mode: "Remote",
        experience: "1-3",
        skills: ["Vue.js", "JavaScript", "CSS"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "10–18 LPA",
        applyUrl: "https://browserstack.com/careers/frontend-dev",
        description: "Build testing platform used by developers worldwide. Work with Vue.js and modern frontend technologies. Remote-first company. Global product with excellent compensation."
    },
    {
        id: 47,
        title: "Data Analyst",
        company: "Byjus",
        location: "Bangalore",
        mode: "Onsite",
        experience: "0-1",
        skills: ["SQL", "Python", "Tableau"],
        source: "LinkedIn",
        postedDaysAgo: 4,
        salaryRange: "3–5 LPA",
        applyUrl: "https://byjus.com/careers/data-analyst",
        description: "Analyze education data and generate insights. Work with large datasets and visualization tools. Impact millions of students' learning. Fast-paced edtech environment."
    },
    {
        id: 48,
        title: "iOS Developer Intern",
        company: "Dream11",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Swift", "iOS", "UIKit"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "₹30k–₹50k/month Internship",
        applyUrl: "https://dream11.com/careers/ios-intern",
        description: "Build fantasy sports app for millions of users. Work with Swift and modern iOS development. High-performance requirements. Learn from experienced mobile developers."
    },
    {
        id: 49,
        title: "Backend Engineer",
        company: "Sharechat",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Go", "Microservices", "Redis"],
        source: "LinkedIn",
        postedDaysAgo: 0,
        salaryRange: "10–18 LPA",
        applyUrl: "https://sharechat.com/careers/backend-eng",
        description: "Build social media platform for Bharat. Work with Go and distributed systems. Handle massive scale and traffic. Fast-growing social media startup."
    },
    {
        id: 50,
        title: "Graduate Trainee Engineer",
        company: "L&T Infotech",
        location: "Mumbai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "SQL", "Web Development"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "3–5 LPA",
        applyUrl: "https://lntinfotech.com/careers/gte",
        description: "Join L&T Infotech's engineering program. Comprehensive training followed by project work. Work on enterprise and infrastructure projects. Stable career with growth opportunities."
    },
    {
        id: 51,
        title: "Full Stack Developer Intern",
        company: "Udaan",
        location: "Bangalore",
        mode: "Remote",
        experience: "Fresher",
        skills: ["React", "Node.js", "MongoDB"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹35k–₹50k/month Internship",
        applyUrl: "https://udaan.com/careers/fullstack-intern",
        description: "Build B2B e-commerce platform for small businesses. Work on both frontend and backend. Modern tech stack. Impact millions of retailers and manufacturers."
    },
    {
        id: 52,
        title: "Security Engineer",
        company: "Razorpay",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "1-3",
        skills: ["Security", "Python", "Penetration Testing"],
        source: "Naukri",
        postedDaysAgo: 3,
        salaryRange: "10–18 LPA",
        applyUrl: "https://razorpay.com/careers/security-eng",
        description: "Secure India's leading payment gateway. Work on security audits and threat detection. Modern security tools and practices. Critical role in fintech security."
    },
    {
        id: 53,
        title: "Angular Developer Intern",
        company: "Tata Elxsi",
        location: "Bangalore",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Angular", "TypeScript", "HTML/CSS"],
        source: "Indeed",
        postedDaysAgo: 6,
        salaryRange: "₹20k–₹35k/month Internship",
        applyUrl: "https://tataelxsi.com/careers/angular-intern",
        description: "Work on product design and engineering projects. Learn Angular and modern web development. Exposure to automotive and healthcare domains. Structured training program."
    },
    {
        id: 54,
        title: "Backend Developer",
        company: "Clevertap",
        location: "Mumbai",
        mode: "Remote",
        experience: "1-3",
        skills: ["Python", "Django", "AWS"],
        source: "LinkedIn",
        postedDaysAgo: 1,
        salaryRange: "10–18 LPA",
        applyUrl: "https://clevertap.com/careers/backend-dev",
        description: "Build customer engagement platform. Work with Python and cloud technologies. Handle billions of events daily. Global SaaS product with strong engineering culture."
    },
    {
        id: 55,
        title: "Software Developer Trainee",
        company: "Hexaware",
        location: "Chennai",
        mode: "Onsite",
        experience: "Fresher",
        skills: ["Java", "Python", "SQL"],
        source: "Naukri",
        postedDaysAgo: 4,
        salaryRange: "3–5 LPA",
        applyUrl: "https://hexaware.com/careers/trainee",
        description: "Join Hexaware's training program. Learn enterprise technologies and work on client projects. Exposure to multiple domains. Good work-life balance and benefits."
    },
    {
        id: 56,
        title: "React Native Developer Intern",
        company: "Pharmeasy",
        location: "Mumbai",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["React Native", "JavaScript", "Mobile"],
        source: "LinkedIn",
        postedDaysAgo: 2,
        salaryRange: "₹25k–₹40k/month Internship",
        applyUrl: "https://pharmeasy.com/careers/rn-intern",
        description: "Build healthcare delivery app. Work with React Native and modern mobile development. Impact millions of users' health. Fast-growing healthtech startup."
    },
    {
        id: 57,
        title: "DevOps Engineer Intern",
        company: "Nutanix",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "Fresher",
        skills: ["Linux", "Docker", "Python"],
        source: "Indeed",
        postedDaysAgo: 5,
        salaryRange: "₹30k–₹45k/month Internship",
        applyUrl: "https://nutanix.com/careers/devops-intern",
        description: "Learn cloud infrastructure at Nutanix. Work with containerization and automation. Mentorship from experienced DevOps engineers. Global product company."
    },
    {
        id: 58,
        title: "Full Stack Engineer",
        company: "Innovaccer",
        location: "Noida",
        mode: "Onsite",
        experience: "1-3",
        skills: ["React", "Node.js", "PostgreSQL"],
        source: "Naukri",
        postedDaysAgo: 1,
        salaryRange: "6–10 LPA",
        applyUrl: "https://innovaccer.com/careers/fullstack-eng",
        description: "Build healthcare data platform. Work on both frontend and backend systems. Modern tech stack. Impact healthcare delivery in US and India."
    },
    {
        id: 59,
        title: "AI/ML Intern",
        company: "Fractal Analytics",
        location: "Mumbai",
        mode: "Remote",
        experience: "Fresher",
        skills: ["Python", "Machine Learning", "Deep Learning"],
        source: "LinkedIn",
        postedDaysAgo: 3,
        salaryRange: "₹30k–₹50k/month Internship",
        applyUrl: "https://fractal.ai/careers/ml-intern",
        description: "Work on AI and ML projects for Fortune 500 clients. Learn from data scientists and ML engineers. Exposure to cutting-edge AI research. Strong analytics culture."
    },
    {
        id: 60,
        title: "Software Engineer",
        company: "Gojek",
        location: "Bangalore",
        mode: "Hybrid",
        experience: "0-1",
        skills: ["Go", "Microservices", "Kubernetes"],
        source: "Indeed",
        postedDaysAgo: 2,
        salaryRange: "6–10 LPA",
        applyUrl: "https://gojek.com/careers/software-eng",
        description: "Build super app for Southeast Asia. Work with Go and distributed systems. Modern engineering practices. Fast-paced startup with global presence."
    }
];
